name: bitespot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  provider: ^6.1.5
  firebase_auth: ^5.7.0
  either_dart: ^1.0.0
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  uuid: ^4.5.1
  cloud_firestore: ^5.6.12
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_polyline_points: ^3.0.1
  http: ^1.4.0
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/images/
   - .env